// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciBilgisiSistemi.Models.Concrete;

namespace OgrenciBilgisiSistemi.Migrations
{
    [DbContext(typeof(OgrenciDbContext))]
    [Migration("20220506065309_Mig1")]
    partial class Mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumBaskanAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.BolumDers", b =>
                {
                    b.Property<int>("BolumDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.HasKey("BolumDersId");

                    b.HasIndex("BolumId");

                    b.HasIndex("DersId");

                    b.ToTable("BolumDers");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("DersAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersHocası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Donem")
                        .HasColumnType("int");

                    b.Property<decimal>("Kredi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DersId");

                    b.HasIndex("BolumId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<int>("Donem")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OgrenciDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OgrenciKayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciDersId");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.BolumDers", b =>
                {
                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ders", b =>
                {
                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Bolum", null)
                        .WithMany("Dersler")
                        .HasForeignKey("BolumId");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ogrenci", b =>
                {
                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.OgrenciDers", b =>
                {
                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Ders", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciBilgisiSistemi.Models.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Bolum", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ders", b =>
                {
                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciBilgisiSistemi.Models.Entities.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
